export default () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3001),
  appUrl: process.env.APP_URL ?? 'http://localhost:3000',
  apiUrl: process.env.API_URL ?? 'http://localhost:3001',
  databaseUrl: process.env.DATABASE_URL ?? '',
  redisUrl: process.env.REDIS_URL ?? 'redis://localhost:6379',
  jwtSecret: process.env.JWT_SECRET ?? '',
  jwtAccessTokenTtl: process.env.JWT_ACCESS_TOKEN_TTL ?? '15m',
  jwtRefreshTokenTtl: process.env.JWT_REFRESH_TOKEN_TTL ?? '7d',
  twoFactorCodeTtlSeconds: Number(process.env.TWO_FACTOR_CODE_TTL_SECONDS ?? 300),
  auditRetentionDays: Number(process.env.AUDIT_RETENTION_DAYS ?? 180),
  auditRetentionJobIntervalMinutes: Number(
    process.env.AUDIT_RETENTION_JOB_INTERVAL_MINUTES ?? 60,
  ),
  defaultMaxUploadSizeBytes: Number(process.env.DEFAULT_MAX_UPLOAD_SIZE_BYTES ?? 10485760),
  clamAvHost: process.env.CLAMAV_HOST ?? 'localhost',
  clamAvPort: Number(process.env.CLAMAV_PORT ?? 3310),
  virusTotalApiKey: process.env.VIRUSTOTAL_API_KEY ?? '',
  docxAiHeadingEnabled: process.env.DOCX_AI_HEADING_ENABLED ?? 'false',
  docxAiHeadingProvider: process.env.DOCX_AI_HEADING_PROVIDER ?? 'rule-based',
  docxAiHeadingBaseUrl: process.env.DOCX_AI_HEADING_BASE_URL ?? '',
  docxAiHeadingModel: process.env.DOCX_AI_HEADING_MODEL ?? '',
  docxAiHeadingApiKey: process.env.DOCX_AI_HEADING_API_KEY ?? '',
  docxAiHeadingTimeoutMs: Number(process.env.DOCX_AI_HEADING_TIMEOUT_MS ?? 15000),
  parseWorkerConcurrency: Number(process.env.PARSE_WORKER_CONCURRENCY ?? 2),
  libreOfficeBinary: process.env.LIBREOFFICE_BINARY ?? 'soffice',
  pdfConversionTimeoutMs: Number(process.env.PDF_CONVERSION_TIMEOUT_MS ?? 60000),
  sentryDsn: process.env.SENTRY_DSN ?? '',
  citationAiEnabled: process.env.CITATION_AI_ENABLED ?? 'false',
  citationAiProvider: process.env.CITATION_AI_PROVIDER ?? 'openai',
  citationAiBaseUrl: process.env.CITATION_AI_BASE_URL ?? '',
  citationAiModel: process.env.CITATION_AI_MODEL ?? '',
  citationAiApiKey: process.env.CITATION_AI_API_KEY ?? '',
  citationAiTimeoutMs: Number(process.env.CITATION_AI_TIMEOUT_MS ?? 15000),
  storageProvider: process.env.STORAGE_PROVIDER ?? 'minio',
  s3Region: process.env.S3_REGION ?? 'us-east-1',
  s3Bucket: process.env.MINIO_BUCKET ?? process.env.S3_BUCKET ?? 'formatedit',
  s3Endpoint: process.env.MINIO_ENDPOINT ?? '',
  s3AccessKeyId: process.env.S3_ACCESS_KEY_ID ?? '',
  s3SecretAccessKey: process.env.S3_SECRET_ACCESS_KEY ?? '',
  queuePrefix: process.env.QUEUE_PREFIX ?? 'formatedit',
  notificationsWorkerConcurrency: Number(process.env.NOTIFICATIONS_WORKER_CONCURRENCY ?? 4),
  resendApiKey: process.env.RESEND_API_KEY ?? '',
  resendFromAddress: process.env.RESEND_FROM_ADDRESS ?? 'notifications@formatedit.local',
  whatsappToken: process.env.WHATSAPP_TOKEN ?? '',
  whatsappPhoneNumberId: process.env.WHATSAPP_PHONE_NUMBER_ID ?? '',
  whatsappDefaultTemplate: process.env.WHATSAPP_DEFAULT_TEMPLATE ?? '',
  telegramBotToken: process.env.TELEGRAM_BOT_TOKEN ?? '',
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? '',
  stripeWebhookSecret: process.env.STRIPE_WEBHOOK_SECRET ?? '',
  paypalClientId: process.env.PAYPAL_CLIENT_ID ?? '',
  paypalClientSecret: process.env.PAYPAL_CLIENT_SECRET ?? '',
  paypalBaseUrl: process.env.PAYPAL_BASE_URL ?? 'https://api-m.sandbox.paypal.com',
  paypalWebhookId: process.env.PAYPAL_WEBHOOK_ID ?? '',
  sheerIdBaseUrl: process.env.SHEERID_BASE_URL ?? 'https://services.sheerid.com',
  sheerIdApiKey: process.env.SHEERID_API_KEY ?? '',
  sheerIdProgramId: process.env.SHEERID_PROGRAM_ID ?? '',
  sheerIdRedirectBaseUrl:
    process.env.SHEERID_REDIRECT_BASE_URL ?? 'https://services.sheerid.com/verify',
  sheerIdWebhookSecret: process.env.SHEERID_WEBHOOK_SECRET ?? '',
  geoIpProvider: process.env.GEOIP_PROVIDER ?? '',
  googleClientId: process.env.GOOGLE_CLIENT_ID ?? '',
  googleClientSecret: process.env.GOOGLE_CLIENT_SECRET ?? '',
  googleCallbackUrl: process.env.GOOGLE_CALLBACK_URL ?? 'http://localhost:3001/auth/google/callback',
});
